version: '3.7'

services:
  redis:
    container_name: portfolio_redis_container
    image: redis
    volumes:
       - redis:/data/redis
    ports:
      - 6379:6379
    restart: unless-stopped
  mongo:
      container_name: portfolio_mongo_container
      image: mongo
      volumes:
        - mongo:/data/db
      ports:
        - 27017:27017
      restart: unless-stopped

volumes:
    redis:
    mongo:
